name = 'Ayala'
shortName = 'Ayala'
description = 'A 2D adventure game about a homeless cat finding love in Manila'

modules = [
    './main',
    '@rpgjs/mobile-gui',
    '@rpgjs/default-gui',
    '@rpgjs/gamepad'
]

[start]
    map = 'atg'
    graphic = 'mc'
    hitbox = [16, 16]