import Phaser from "phaser";
import { PETS, PET_FRAME } from "../data/pets";
import { PIXEL_CROWD, pixelCrowdTexture, type PixelLookId } from "../data/ambient-roles";
import { versionedUrl } from "../config/buildId";
import { cacheLoadedFiles } from "../utils/offlineCache";

/** Registry keys: game assets loaded (StartScene waits for this), and load progress 0..1. */
export const ASSETS_READY = "ASSETS_READY";
export const ASSET_PROGRESS = "ASSET_PROGRESS";

/**
 * Per-request cap so a stalled download cannot leave ASSETS_READY false.
 * Phaser still retries twice (loader.maxRetries), then the loader's complete
 * event reports the failure and StartScene offers a retry.
 */
export const ASSET_XHR_TIMEOUT_MS = 45_000;

export class BootScene extends Phaser.Scene {
  constructor() {
    super({ key: "BootScene" });
  }

  init(): void {
    if (typeof window === "undefined" || typeof window.matchMedia !== "function") {
      this.registry.set("MOTION_REDUCED", false);
      return;
    }
    const mq = window.matchMedia("(prefers-reduced-motion: reduce)");
    this.registry.set("MOTION_REDUCED", mq.matches);
    mq.addEventListener("change", () => {
      this.registry.set("MOTION_REDUCED", mq.matches);
    });
  }

  /** Everything a game needs to start. Music is queued separately, after these. */
  private queueGameAssets(): void {
    this.load.image("park-tiles", "assets/tilesets/park-tiles.png");
    this.load.image("trees-pale", "assets/tilesets/trees-pale.png");
    this.load.image("plants", "assets/tilesets/plants.png");
    this.load.image("atg-ground", "assets/tilesets/atg-ground.png");
    this.load.tilemapTiledJSON("atg", "assets/tilemaps/atg.json");
    this.load.image("carabao_small", "assets/sprites/carabao_small.png");
    this.load.image("hornbill_small", "assets/sprites/hornbill_small.png");
    this.load.image("starbucks_logo", "assets/sprites/starbucks.png");
    // Top-down traffic + story cars, generated by scripts/generate-vehicles.mjs.
    this.load.atlas("vehicles", "assets/sprites/vehicles.png", "assets/sprites/vehicles.json");

    // Cat spritesheets: 8 cols x 10 rows of 32x32 frames
    const cats = ["mammacat", "blacky", "tiger", "jayco", "fluffy"];
    for (const key of cats) {
      this.load.spritesheet(key, `assets/sprites/${key}.png`, {
        frameWidth: 32,
        frameHeight: 32,
      });
    }

    // MammaCat dedicated spritesheets (48x48 frames, single-row strips)
    const mcSheets: Array<[string, string]> = [
      ["mc_stand8", "mammacat_stand_8directions"],
      ["mc_walk_e", "mammacat_walk_east"],
      ["mc_walk_w", "mammacat_walk_west"],
      ["mc_walk_n", "mammacat_walk_north"],
      ["mc_walk_s", "mammacat_walk_south"],
      ["mc_run_e", "mammacat_run_east"],
      ["mc_run_w", "mammacat_run_west"],
      ["mc_run_n", "mammacat_run_north"],
      ["mc_run_s", "mammacat_run_south"],
      ["mc_sit_idle_e", "mammacat_seated_idle_east"],
      ["mc_sit_idle_w", "mammacat_seated_idle_west"],
      ["mc_stand_idle_e", "mammacat_standing_idle_east"],
      ["mc_stand_idle_w", "mammacat_standing_idle_west"],
      ["mc_greet_e", "mammacat_greeting_east"],
      ["mc_greet_w", "mammacat_greeting_west"],
      ["mc_drink_e", "mammacat_drinking_east"],
      ["mc_drink_w", "mammacat_drinking_west"],
    ];
    for (const [key, file] of mcSheets) {
      this.load.spritesheet(key, `assets/sprites/${file}.png`, {
        frameWidth: 48,
        frameHeight: 48,
      });
    }

    // MammaCat sleep: single 64x64 image (scaled down at display time)
    this.load.image("mc_sleep", "assets/sprites/mammacat_sleep_64x64.png");

    // MammaCat catloaf: single 48x48 image (alert rest pose)
    this.load.image("mc_catloaf", "assets/sprites/mamma_catloaf.png");

    // Guard spritesheet: 8 cols x 7 rows of 64x64 frames
    this.load.spritesheet("guard", "assets/sprites/guard.png", {
      frameWidth: 64,
      frameHeight: 64,
    });

    // PixelLab pets (Cat cat, Mittens, Ella): 92x92 cells, layout in src/data/pets.ts
    for (const pet of Object.values(PETS)) {
      this.load.spritesheet(pet.texture, `assets/sprites/pets/${pet.texture.replace("pet_", "")}.png`, { frameWidth: PET_FRAME, frameHeight: PET_FRAME });
    }

    // Dog spritesheets: 4 cols x 9 rows of 32x32 frames
    const dogs = ["SmallDog", "WhiteDog", "BrownDog"];
    for (const key of dogs) {
      this.load.spritesheet(key, `assets/sprites/${key}.png`, {
        frameWidth: 32,
        frameHeight: 32,
      });
    }

    // Feeder spritesheets (48x48 frames, single-row strips)
    const feederSheets: Array<[string, string]> = [
      ["feeder_stand", "feeder_stand"],
      ["feeder_walk_e", "feeder_walk_east"],
      ["feeder_walk_w", "feeder_walk_west"],
    ];
    for (const [key, file] of feederSheets) {
      this.load.spritesheet(key, `assets/sprites/${file}.png`, {
        frameWidth: 48,
        frameHeight: 48,
      });
    }

    // Ben spritesheets (68x68 frames, single-row strips)
    const benSheets: Array<[string, string]> = [
      ["ben_stand", "ben_stand"],
      ["ben_walk_e", "ben_walk_east"],
      ["ben_walk_w", "ben_walk_west"],
      ["ben_walk_n", "ben_walk_north"],
      ["ben_walk_s", "ben_walk_south"],
      ["ben_crouch_e", "ben_crouch_east"],
      ["ben_crouch_w", "ben_crouch_west"],
    ];
    for (const [key, file] of benSheets) {
      this.load.spritesheet(key, `assets/sprites/${file}.png`, {
        frameWidth: 68,
        frameHeight: 68,
      });
    }

    // Female jogger spritesheets (68x68 frames, single-row strips)
    const joggerSheets: Array<[string, string]> = [
      ["jogger_stand", "jogger_stand"],
      ["jogger_run_e", "jogger_run_east"],
      ["jogger_run_w", "jogger_run_west"],
      ["jogger_run_n", "jogger_run_north"],
      ["jogger_run_s", "jogger_run_south"],
    ];
    for (const [key, file] of joggerSheets) {
      this.load.spritesheet(key, `assets/sprites/${file}.png`, {
        frameWidth: 68,
        frameHeight: 68,
      });
    }

    // Male jogger directional spritesheets (48x48 frames, single-row strips of 8)
    const mjogSheets: Array<[string, string]> = [
      ["mjog_stand", "male_jogger_stand"],
      ["mjog_run_e", "male_jogger_run_east"],
      ["mjog_run_w", "male_jogger_run_west"],
      ["mjog_run_n", "male_jogger_run_north"],
      ["mjog_run_s", "male_jogger_run_south"],
    ];
    for (const [key, file] of mjogSheets) {
      this.load.spritesheet(key, `assets/sprites/${file}.png`, {
        frameWidth: 48,
        frameHeight: 48,
      });
    }

    // Legacy dog walker sheet (7 cols x 3 rows, 50x45) — kept for revert.
    // To revert: restore DOGWALKER_PROFILE in HumanNPC.ts to use key "dogwalker".
    this.load.spritesheet("dogwalker", "assets/sprites/dogwalker.png", {
      frameWidth: 50,
      frameHeight: 45,
    });

    // Ambient crowd extras (AmbientCrowdSystem) — anonymous art only, under new keys.
    // girl.png: 8 cols x 6 rows of 150x85 side-view frames (idle, walk, phone, phone-walk, run, sit/lie).
    for (const key of Object.keys(PIXEL_CROWD) as PixelLookId[]) {
      this.load.spritesheet(pixelCrowdTexture(key), `assets/sprites/crowd/${key}.png`, { frameWidth: 68, frameHeight: 68 });
    }
    this.load.spritesheet("crowd_girl", "assets/sprites/girl.png", {
      frameWidth: 150,
      frameHeight: 85,
    });
    // The legacy dogwalker.png is really 14 cols x 3 rows of 25x45 fedora-man figures;
    // the "dogwalker" key above keeps its old 50x45 slicing.
    this.load.spritesheet("crowd_fedora", "assets/sprites/dogwalker.png", {
      frameWidth: 25,
      frameHeight: 45,
    });

    // Female dog walker directional spritesheets (48x48 frames, single-row strips)
    const dwSheets: Array<[string, string]> = [
      ["dw_e", "female_dogwalker_east"],
      ["dw_w", "female_dowwalker_west"], // filename has typo ("dowwalker")
      ["dw_n", "female_dogwalker_north"],
      ["dw_s", "female_dogwalker_south"],
    ];
    for (const [key, file] of dwSheets) {
      this.load.spritesheet(key, `assets/sprites/${file}.png`, {
        frameWidth: 48,
        frameHeight: 48,
      });
    }

    // Camille spritesheets (68x68 frames, single-row strips)
    const camSheets: Array<[string, string]> = [
      ["cam_stand", "cam_stand"],
      ["cam_walk_e", "cam_walk_east"],
      ["cam_walk_w", "cam_walk_west"],
      ["cam_walk_n", "cam_walk_north"],
      ["cam_walk_s", "cam_walk_south"],
      ["cam_crouch_e", "cam_crouch_east"],
      ["cam_crouch_w", "cam_crouch_west"],
    ];
    for (const [key, file] of camSheets) {
      this.load.spritesheet(key, `assets/sprites/${file}.png`, {
        frameWidth: 68,
        frameHeight: 68,
      });
    }

    // Manu spritesheets (68x68 frames, single-row strips)
    const manuSheets: Array<[string, string]> = [
      ["manu_stand", "manu_stand"],
      ["manu_walk_e", "manu_walk_east"],
      ["manu_walk_w", "manu_walk_west"],
      ["manu_walk_n", "manu_walk_north"],
      ["manu_walk_s", "manu_walk_south"],
      ["manu_crouch_e", "manu_crouch_east"],
      ["manu_crouch_w", "manu_crouch_west"],
    ];
    for (const [key, file] of manuSheets) {
      this.load.spritesheet(key, `assets/sprites/${file}.png`, {
        frameWidth: 68,
        frameHeight: 68,
      });
    }

    // Kish spritesheets (68x68 frames, single-row strips, no crouch)
    const kishSheets: Array<[string, string]> = [
      ["kish_stand", "Kish_stand"], // capital K in filename
      ["kish_walk_e", "kish_walk_east"],
      ["kish_walk_w", "kish_walk_west"],
      ["kish_walk_n", "kish_walk_north"],
      ["kish_walk_s", "kish_walk_south"],
      // her other outfit (same layout), worn on alternate days — see kishProfileForDay
      ["kishdale_stand", "Kishdale_stand"],
      ["kishdale_walk_e", "kishdale_walk_east"],
      ["kishdale_walk_w", "kishdale_walk_west"],
      ["kishdale_walk_n", "kishdale_walk_north"],
      ["kishdale_walk_s", "kishdale_walk_south"],
    ];
    for (const [key, file] of kishSheets) {
      this.load.spritesheet(key, `assets/sprites/${file}.png`, {
        frameWidth: 68,
        frameHeight: 68,
      });
    }

    // Snatcher spritesheets (68x68 frames, single-row strips)
    const snatcherSheets: Array<[string, string]> = [
      ["snatcher_stand", "snatcher1_stand"],
      ["snatcher_walk_e", "snatcher1_walk_east"],
      ["snatcher_walk_w", "snatcher1_walk_west"],
      ["snatcher_walk_n", "snatcher1_walk_north"],
      ["snatcher_walk_s", "snatcher1_walk_south"],
      ["snatcher2_stand", "snatcher2_stand"],
      ["snatcher2_walk_e", "snatcher2_walk_east"],
      ["snatcher2_walk_w", "snatcher2_walk_west"],
      ["snatcher2_walk_n", "snatcher2_walk_north"],
      ["snatcher2_walk_s", "snatcher2_walk_south"],
    ];
    for (const [key, file] of snatcherSheets) {
      this.load.spritesheet(key, `assets/sprites/${file}.png`, {
        frameWidth: 68,
        frameHeight: 68,
      });
    }

    // Audio SFX. The music loops load after the title screen is up (see create()).
    this.load.audio("sfx_meow_happy", "assets/sounds/meow_happy.mp3");
    this.load.audio("sfx_meow_kitten", "assets/sounds/meow_kitten.mp3");
    this.load.audio("sfx_cat_growl_warning", "assets/sounds/cat_growl_warning.mp3");
    // Traffic reactions to Mamma Cat on the road (synthesised by scripts/generate-sfx.mjs).
    this.load.audio("sfx_tyre_screech", "assets/sounds/tyre_screech.wav");
    this.load.audio("sfx_car_horn", "assets/sounds/car_horn.wav");

    // Lucide volume-2 / volume-x glyphs for the HUD mute toggle. Rasterised
    // at 20x20 to match the HUD icon slot exactly (avoids runtime scaling).
    this.load.svg("icon_volume_on", "assets/icons/volume-2.svg", { width: 20, height: 20 });
    this.load.svg("icon_volume_off", "assets/icons/volume-x.svg", { width: 20, height: 20 });
  }

  create(): void {
    makeLightTextures(this);
    makeStreetColonyTextures(this);

    // Title first: StartScene needs no assets, so it shows at once and the game loads behind
    // it (StartScene starts a game only once ASSETS_READY). Then the music and the Sunday track,
    // which AudioSystem starts the moment each is cached. This scene keeps running because it
    // owns the loader; it stops itself when everything is in.
    this.registry.set(ASSETS_READY, false);
    this.registry.set(ASSET_PROGRESS, 0);
    this.scene.launch("StartScene");

    // File xhrSettings.timeout defaults to 0 and overrides this.load.xhr in MergeXHRSettings,
    // so a loader-only timeout never fires. Set both before the queue starts.
    this.load.xhr.timeout = ASSET_XHR_TIMEOUT_MS;
    this.load.on("addfile", (_key: string, type: string, _loader: unknown, file: Phaser.Loader.File) => {
      file.xhrSettings.timeout = ASSET_XHR_TIMEOUT_MS;
      // Audio (~7 MB) keeps its plain URL: mixing it across builds is harmless, and after a deploy
      // it then revalidates (ETag) instead of downloading again.
      if (typeof file.url === "string" && type !== "audio") file.url = versionedUrl(file.url);
    });
    this.load.on("progress", (p: number) => this.registry.set(ASSET_PROGRESS, p));
    this.queueGameAssets();
    this.load.once("complete", (_loader: unknown, _ok: number, failed: number) => {
      this.load.removeAllListeners("progress");
      if (failed > 0) {
        // a game started without its map or sprites would crash; StartScene offers a retry
        this.registry.set(ASSETS_READY, "failed");
        this.scene.stop();
        return;
      }
      this.registry.set(ASSETS_READY, true);
      cacheLoadedFiles(); // playable now: keep it offline even if the music never finishes
      this.load.audio("bgm_ayala", "assets/sounds/ayala_loop_Luminous Rain.mp3");
      this.load.audio("bgm_snatcher", "assets/sounds/snatcher_loop_Stay the Course.mp3");
      // generated placeholder (scripts/generate-sfx.mjs) until a licensed royalty-free track replaces the file
      this.load.audio("sfx_sunday_lights", "assets/sounds/sunday_lights.wav");
      this.load.once("complete", () => {
        cacheLoadedFiles();
        this.scene.stop();
      });
      this.load.start();
    });
    this.load.start();
  }
}

/** Soft additive light sprites for lamps and headlights (night). */
function makeLightTextures(scene: Phaser.Scene): void {
  if (!scene.textures.exists("light_glow")) {
    const tex = scene.textures.createCanvas("light_glow", 128, 128);
    const ctx = tex?.getContext();
    if (tex && ctx) {
      const g = ctx.createRadialGradient(64, 64, 0, 64, 64, 64);
      g.addColorStop(0, "rgba(255,255,255,1)");
      g.addColorStop(0.35, "rgba(255,255,255,0.45)");
      g.addColorStop(1, "rgba(255,255,255,0)");
      ctx.fillStyle = g;
      ctx.fillRect(0, 0, 128, 128);
      tex.refresh();
    }
  }
  if (!scene.textures.exists("light_beam")) {
    // a cone opening to the right from its left-middle point (origin 0, 0.5)
    const tex = scene.textures.createCanvas("light_beam", 160, 96);
    const ctx = tex?.getContext();
    if (tex && ctx) {
      const g = ctx.createRadialGradient(0, 48, 0, 0, 48, 160);
      g.addColorStop(0, "rgba(255,255,255,0.9)");
      g.addColorStop(1, "rgba(255,255,255,0)");
      ctx.fillStyle = g;
      ctx.beginPath();
      ctx.moveTo(0, 40);
      ctx.lineTo(160, 0);
      ctx.lineTo(160, 96);
      ctx.lineTo(0, 56);
      ctx.closePath();
      ctx.fill();
      tex.refresh();
    }
  }
}

/** Draw `rows` (one char per pixel, "." clear) into a canvas texture `key`, colouring by `palette`. */
function pixelTexture(scene: Phaser.Scene, key: string, rows: readonly string[], palette: Record<string, string>): void {
  if (scene.textures.exists(key)) return;
  const w = Math.max(...rows.map((r) => r.length));
  const tex = scene.textures.createCanvas(key, w, rows.length);
  const ctx = tex?.getContext();
  if (!tex || !ctx) return;
  rows.forEach((row, y) =>
    [...row].forEach((ch, x) => {
      const colour = palette[ch];
      if (!colour) return;
      ctx.fillStyle = colour;
      ctx.fillRect(x, y, 1, 1);
    }),
  );
  tex.refresh();
}

/** The street colony's props across Ayala Ave: a cat house, food and water bowls, Simba's rock. */
function makeStreetColonyTextures(scene: Phaser.Scene): void {
  pixelTexture(
    scene,
    "cat_house",
    [
      "........oooo........",
      "......ooRRRRoo......",
      "....ooRRRRRRRRoo....",
      "..ooRRRRRRRRRRRRoo..",
      ".orrrrrrrrrrrrrrrro.",
      "orrrrrrrrrrrrrrrrrro",
      "oooooooooooooooooooo",
      ".owwwwwwwwwwwwwwwwo.",
      ".owwwwwwddddwwwwwwo.",
      ".owWwwwddddddwwwWwo.",
      ".owwwwwddddddwwwwwo.",
      ".owWwwwddddddwwwWwo.",
      ".owwwwwddddddwwwwwo.",
      ".oWWWWWddddddWWWWWo.",
      ".oooooooooooooooooo.",
    ],
    { o: "#3b2618", R: "#b0503a", r: "#8a3b2a", w: "#c9955a", W: "#9c6b3c", d: "#24170f" },
  );
  const bowl = (key: string, inside: string, glint: string, plastic: string, rim: string) =>
    pixelTexture(
      scene,
      key,
      ["..BBBBBBBB..", ".BiiGiiiiiB.", "BbiiiiiGiibB", "BbbbbbbbbbbB", ".BbbbbbbbbB.", "..BBBBBBBB.."],
      { B: rim, b: plastic, i: inside, G: glint },
    );
  bowl("cat_bowl_food", "#8b5a2b", "#b07a42", "#c0392b", "#7d2318");
  bowl("cat_bowl_water", "#5fa8d8", "#c6ecff", "#9aa5ad", "#5d666c");

  // a big rounded boulder with a flat, sunlit top for a cat to sit on
  if (!scene.textures.exists("cat_rock")) {
    const w = 40;
    const h = 26;
    const tex = scene.textures.createCanvas("cat_rock", w, h);
    const ctx = tex?.getContext();
    if (tex && ctx) {
      const inBody = (x: number, y: number) => ((x - 20) / 19.5) ** 2 + ((y - 15) / 10.5) ** 2 <= 1;
      const inTop = (x: number, y: number) => ((x - 20) / 15) ** 2 + ((y - 10) / 7) ** 2 <= 1;
      for (let y = 0; y < h; y++)
        for (let x = 0; x < w; x++) {
          if (!inBody(x, y) && !inTop(x, y)) continue;
          const edge = ([[1, 0], [-1, 0], [0, 1], [0, -1]] as const).some(([dx, dy]) => !inBody(x + dx, y + dy) && !inTop(x + dx, y + dy));
          const speck = (x * 7 + y * 13) % 11 === 0; // fixed grain, no randomness
          ctx.fillStyle = edge ? "#45423f" : inTop(x, y) ? (y < 7 && x > 12 && x < 26 ? "#c4c1ba" : speck ? "#97938d" : "#aaa69f") : y > 20 ? "#5f5c58" : speck ? "#6f6c67" : "#86827c";
          ctx.fillRect(x, y, 1, 1);
        }
      tex.refresh();
    }
  }
}
